name: Deploy Site Estático

on:
  push:
    branches:
      - TESTE
      - PROD

permissions:
  contents: read
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v5

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PAGES_REPO_TOKEN }}
          publish_dir: .  # publica a raiz do repositório, ajuste se quiser outra pasta
